### ISSUE TITLE
Handle on-going call when WiFi signal drops

### ISSUE THREAD

**Issue by vicelversa** [indianpoptart/RadioControl#42]
**Test environment:**
RadioControl is Enabled
Cell service disabled via Alternate root command
On-going phone call over WiFi

**Problem:**
If WiFi is lost while on phone call, the call will drop.

**Solution:**
Enable cell service at start of phone call for fallback.  

**Expected behavior:**
Phone call will initially connect over WiFi and gracefully fallback to cell service if WiFi signal drops.

**Comment by vicelversa** [comment]
Just noticed this is potential dupe to https://github.com/indianpoptart/RadioControl/issues/8

However that issue specifically involves when using airplane mode (as opposed to alt. root command).  However the solution is likely the same for both.

**Comment by indianpoptart** [comment]
I sort of meant for #8 to be the same as this, but I like this issue because it has a better explaination of the problem

I am going to add a call setting where it checks if you are on a call, then detects the link speed/signal strength and will turn on the cell radio(or turn off airplane mode) 

I suggest using the alt. root command if you do a lot of those kinds of calls, as that method is much faster than traditional airplane toggle. 

**TODO/IDEAS:**

1. Either disable airplane mode when a call goes on(to minimize any issues, may be more battery intense if it's constantly detecting a call. This could disable the main app when a call is in progress, then reenable it if the app was previously enabled
2. Detect when a WiFi signal degrades, then switch the cell radio back on, this can be problematic if the caller goes into a car, as when you drive away, the wifi signal kinda stays there even though there is none. 

I may edit this or add another comment if I add this to an upcoming beta

**Comment by indianpoptart** [comment]
Added in v4.1-Beta8

Found here:
Settings->Phone Settings -> Enable Phone Call Check
